# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRecordSeleniumIDE():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_recordSeleniumIDE(self):
    # Test name: record_SeleniumIDE
    # Step # | name | target | value | comment
    # 1 | open | /ru/ |  | 
    self.driver.get("http://selenium1py.pythonanywhere.com/ru/")
    # 2 | setWindowSize | 1601x874 |  | 
    self.driver.set_window_size(1601, 874)
    # 3 | click | id=login_link |  | 
    self.driver.find_element(By.ID, "login_link").click()
    # 4 | click | id=id_registration-email |  | 
    self.driver.find_element(By.ID, "id_registration-email").click()
    # 5 | type | id=id_registration-email | qwerty | 
    self.driver.find_element(By.ID, "id_registration-email").send_keys("qwerty")
    # 6 | type | id=id_registration-email | qwerty15963@gmail.com | 
    self.driver.find_element(By.ID, "id_registration-email").send_keys("qwerty15963@gmail.com")
    # 7 | type | id=id_registration-password1 | asdqwe123#_159963 | 
    self.driver.find_element(By.ID, "id_registration-password1").send_keys("asdqwe123#_159963")
    # 8 | type | id=id_registration-password2 | asdqwe123#_15963 | 
    self.driver.find_element(By.ID, "id_registration-password2").send_keys("asdqwe123#_15963")
    # 9 | click | name=registration_submit |  | 
    self.driver.find_element(By.NAME, "registration_submit").click()
    # 10 | click | id=id_registration-password1 |  | 
    self.driver.find_element(By.ID, "id_registration-password1").click()
    # 11 | type | id=id_registration-password1 | asdqwe | 
    self.driver.find_element(By.ID, "id_registration-password1").send_keys("asdqwe")
    # 12 | type | id=id_registration-password1 | asdqwe123# | 
    self.driver.find_element(By.ID, "id_registration-password1").send_keys("asdqwe123#")
    # 13 | type | id=id_registration-password1 | asdqwe123#_15963 | 
    self.driver.find_element(By.ID, "id_registration-password1").send_keys("asdqwe123#_15963")
    # 14 | type | id=id_registration-password2 | asdqwe123 | 
    self.driver.find_element(By.ID, "id_registration-password2").send_keys("asdqwe123")
    # 15 | type | id=id_registration-password2 | asdqwe123#_ | 
    self.driver.find_element(By.ID, "id_registration-password2").send_keys("asdqwe123#_")
    # 16 | type | id=id_registration-password2 | asdqwe123#_15963 | 
    self.driver.find_element(By.ID, "id_registration-password2").send_keys("asdqwe123#_15963")
    # 17 | click | name=registration_submit |  | 
    self.driver.find_element(By.NAME, "registration_submit").click()
  
